### ISSUE TITLE
Cookie exception on initial third party login (signup)

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-mobile#8]
# Steps to reproduce

- Open SignIn WebView
- Sign in with a GitHub/Google account that is not connected to Sentry

**Expected**
- Logged in

**Actual**
- Exception is thrown

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: FormatException: Invalid character in cookie value, code unit: '92' (at character 45)
"6bf034c9d8179e15563e9b0607ea6687bef3e3b2$[[\"__json_message\"\0540\05425\0...
                                            ^

#0      _Cookie._validateValue (dart:_http/http_headers.dart:1106:9)
#1      new _Cookie (dart:_http/http_headers.dart:922:18)
#2      new Cookie (dart:_http:1050:52)
#3      WebviewCookieManager.getCookies.<anonymous closure>.<anonymous closure> (package:webview_cookie_manager/webview_cookie_manager.dart:33:26)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#6      new List.from (dart:core-patch/array_patch.dart:38:29)
#7      new List.of (dart:core-patch/array_patch.dart:68:17)
#8      ListIterable.toList (dart:_internal/iterable.dart:211:44)
#9      WebviewCookieManager.getCookies.<anonymous closure> (package:webview_cookie_manager/webview_c<…>
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: FormatException: Invalid character in cookie value, code unit: '92' (at character 45)
"6bf034c9d8179e15563e9b0607ea6687bef3e3b2$[[\"__json_message\"\0540\05425\0...
                                            ^

#0      _Cookie._validateValue (dart:_http/http_headers.dart:1106:9)
#1      new _Cookie (dart:_http/http_headers.dart:922:18)
#2      new Cookie (dart:_http:1050:52)
#3      WebviewCookieManager.getCookies.<anonymous closure>.<anonymous closure> (package:webview_cookie_manager/webview_cookie_manager.dart:33:26)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#6      new List.from (dart:core-patch/array_patch.dart:38:29)
#7      new List.of (dart:core-patch/array_patch.dart:68:17)
#8      ListIterable.toList (dart:_internal/iterable.dart:211:44)
#9      WebviewCookieManager.getCookies.<anonymous closure> (package:webview_cookie_manager/webview_c<…>
```

**Comment by denrase** [comment]
Just tried to reproduce this. Both Google and GitHub worked for login when initially connecting them.
